<%@ Page Language="C#" %>
<%
    var db = new PPPEntities();
    var projectId = Convert.ToInt32(Request["projectId"]);
    var subId = Convert.ToInt32(Request["subId"]);
    var risk = db.RiskClassificationForm.Where(x => x.ProjectId == projectId && x.type == "1");

    if (risk.Any())
    {
        var maxSubId = Convert.ToInt32(risk.Max(x => x.SubId));
        var from = risk.First(x => x.SubId == maxSubId);
        var to = db.RiskClassificationForm.First(x => x.ProjectId == projectId && x.SubId == subId && x.type == "2");
        if (from != null && to != null)
        {
            to.c1 = from.c1;
            to.c2 = from.c2;
            to.c3 = from.c3;
            to.c4 = from.c4;
            to.c5 = from.c5;
            to.c6 = from.c6;
            to.c7 = from.c7;
            to.t1 = from.t1;
            to.t2 = from.t2;
            to.t3 = from.t3;
            to.t4 = from.t4;
            to.t5 = from.t5;
            to.t6 = from.t6;
            to.t7 = from.t7;
            to.t8 = from.t8;
            to.t9 = from.t9;
            to.t10 = from.t10;
            to.t11 = from.t11;
            to.t12 = from.t12;
            to.t13 = from.t13;
            to.t14 = from.t14;
            to.t15 = from.t15;
            to.t16 = from.t16;
            to.t17 = from.t17;
            to.t18 = from.t18;
            to.t19 = from.t19;
            to.t20 = from.t20;
            to.t21 = from.t21;
            to.t22 = from.t22;
            to.t23 = from.t23;
            to.t24 = from.t24;
            to.t25 = from.t25;
            to.t26 = from.t26;
            to.t27 = from.t27;
            to.t28 = from.t28;
            to.t29 = from.t29;
            to.t30 = from.t30;
            to.t31 = from.t31;
            to.t32 = from.t32;
            to.t33 = from.t33;
            to.t34 = from.t34;
            to.t35 = from.t35;
            to.t36 = from.t36;
            to.t37 = from.t37;
            to.t38 = from.t38;
            to.t39 = from.t39;
            to.t40 = from.t40;
            to.t41 = from.t41;
            to.t42 = from.t42;
            to.t43 = from.t43;
            to.t44 = from.t44;
            to.t45 = from.t45;
            to.t46 = from.t46;
            to.t47 = from.t47;
            to.t48 = from.t48;
            to.t49 = from.t49;
            to.t50 = from.t50;
            to.t51 = from.t51;
            to.t52 = from.t52;
            to.t53 = from.t53;
            to.t54 = from.t54;
            to.t55 = from.t55;
            to.t56 = from.t56;
            to.t57 = from.t57;
            to.t58 = from.t58;
            to.t59 = from.t59;
            to.t60 = from.t60;
            to.t61 = from.t61;
            to.t62 = from.t62;
            to.t63 = from.t63;
            to.t64 = from.t64;
            to.t65 = from.t65;
            to.t66 = from.t66;
            to.t67 = from.t67;
            to.t68 = from.t68;
            to.t69 = from.t69;
            to.t70 = from.t70;
            to.t71 = from.t71;
            to.t72 = from.t72;
            to.t73 = from.t73;
            to.t74 = from.t74;
            to.t75 = from.t75;
            to.t76 = from.t76;
            to.r1 = from.r1;
            to.r2 = from.r2;
            to.r3 = from.r3;
            to.r4 = from.r4;
            to.r5 = from.r5;
            to.r6 = from.r6;
            to.r7 = from.r7;
            to.r8 = from.r8;
            to.r9 = from.r9;
            to.r10 = from.r10;
            to.r11 = from.r11;
            to.r12 = from.r12;
            to.r13 = from.r13;
            to.r14 = from.r14;
            to.r15 = from.r15;
            to.r16 = from.r16;
            to.r17 = from.r17;
            to.r18 = from.r18;
            to.r19 = from.r19;
            to.r20 = from.r20;
            to.r21 = from.r21;
            to.s1 = from.s1;
            to.s2 = from.s2;
            to.s3 = from.s3;
            to.s4 = from.s4;
            to.s5 = from.s5;
            to.s6 = from.s6;
            to.s7 = from.s7;
            to.s8 = from.s8;
            to.s9 = from.s9;
            to.s10 = from.s10;
            to.s11 = from.s11;
            to.s12 = from.s12;
            to.s13 = from.s13;
            to.s14 = from.s14;
            to.s15 = from.s15;
            to.s16 = from.s16;
            to.s17 = from.s17;
            to.s18 = from.s18;
            to.s19 = from.s19;
            to.s20 = from.s20;
            to.s21 = from.s21;
            
            to.s22 = from.s22;
            to.s23 = from.s23;
            to.s24 = from.s24;
            to.r22 = from.r22;
            to.r23 = from.r23;
            to.r24 = from.r24;
            to.t77 = from.t77;
            to.t78 = from.t78;
            to.t79 = from.t79;
            to.t80 = from.t80;
            to.t81 = from.t81;
            to.t82 = from.t82;
            to.t83 = from.t83;
            to.t84 = from.t84;
            to.t85 = from.t85;
            db.SaveChanges();
            var sb = new StringBuilder();
            sb.AppendFormat("{{");
            sb.AppendFormat("\"{0}\":\"{1}\", ", "ErrorCode", "0");
            sb.AppendFormat("\"{0}\":\"{1}\"  ", "ErrorMessage", "OK.");
            sb.AppendFormat("}}");
            Response.Write(sb.ToString());
        }
        else
        {
            var sb = new StringBuilder();
            sb.AppendFormat("{{");
            sb.AppendFormat("\"{0}\":\"{1}\", ", "ErrorCode", "-2");
            sb.AppendFormat("\"{0}\":\"{1}\"  ", "ErrorMessage", "Invalid Param.");
            sb.AppendFormat("}}");
            Response.Write(sb.ToString());
        }
    }
    else
    {
        var sb = new StringBuilder();
        sb.AppendFormat("{{");
        sb.AppendFormat("\"{0}\":\"{1}\", ", "ErrorCode", "-1");
        sb.AppendFormat("\"{0}\":\"{1}\"  ", "ErrorMessage", "Invalid Proposal Risk Form.");
        sb.AppendFormat("}}");
        Response.Write(sb.ToString());
    }
     %>